[workspace]
authors = ["Lim Junmin <dsgoat99@naver.com>"]
channels = ["conda-forge"]
name = "03_Bithumb"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
start = "python coin.py"

[dependencies]
python = ">=3.14.0,<3.15"

[pypi-dependencies]
pybithumb = ">=1.0.21, <2"
